version: "2"

services:
  github-exporter:
    tty: true
    stdin_open: true
    expose:
      - 9171
    ports:
      - 9171:9171
    image: 346612984731.dkr.ecr.ap-southeast-1.amazonaws.com/mantle-github-exporter:latest
    environment:
      - REPOS=<REPOS you want to monitor>
      - GITHUB_TOKEN=<your github api token>
